import {Dimensions, StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: Dimensions.get('window').height,
  },
  backgroundImage: {
    flex: 1,
    height: Dimensions.get('window').height,
  },
  button: {
    width: '85%',
    height: 55,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: '#FF5858',
    alignSelf: 'center',
  },
  buttonText: {
    fontSize: 18,
    color: 'white',
    fontWeight: 'bold',
    fontFamily: 'Poppins-Bold',
  },
  onboardingTitle: {
    fontFamily: 'Poppins-Bold',
    fontSize: 22,
    color: 'white',
    textAlign: 'center',
    paddingHorizontal: 40,
    marginBottom: 40,
  },
  title: {
    fontFamily: 'Poppins-Bold',
    fontSize: 25,
    color: 'white',
    textAlign: 'center',
    padding: 20,
    textDecorationLine: 'underline',
  },
  card: {
    width: '90%',
    alignSelf: 'center',
    height: 100,
    borderRadius: 8,
    backgroundColor: '#AFEA0D',
    flexDirection: 'row',
    padding: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 30,
  },
  cardImage: {
    width: '30%',
    height: 90,
    resizeMode: 'contain',
    borderRadius: 8,
  },
  cardText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 20,
    color: 'black',
    opacity: 0.8,
  },
  cardIcon: {
    width: 50,
    height: 50,
  },
  dayCard: {
    width: '90%',
    alignSelf: 'center',
    height: 80,
    borderRadius: 8,
    backgroundColor: '#FEBB0E',
    flexDirection: 'row',
    padding: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 30,
  },
  dayCardImage: {
    resizeMode: 'contain',
    borderRadius: 8,
    height: 75,
    width: 75,
  },
  dayCardText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    color: 'black',
    opacity: 0.8,
    width: '60%',
    textAlign: 'center',
  },
  dayCardIcon: {
    width: 30,
    height: 30,
  },
  detailImage: {
    resizeMode: 'contain',
    alignSelf: 'center',
    width: '70%',
  },
  detailTitle: {
    fontFamily: 'Poppins-Bold',
    fontSize: 25,
    textAlign: 'center',
    padding: 20,
    color: '#FEBB0E',
  },
  detailSubtitle: {
    fontFamily: 'Poppins-Thin',
    fontSize: 18,
    textAlign: 'justify',
    padding: 20,
    color: '#FEBB0E',
  },
});
